name: CustomSMPPlugin
main: me.aroxu.customsmp.CustomSMPPlugin
version: $version
api-version: '1.17'

author: aroxu

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.21
  - org.jetbrains.exposed:exposed-core:0.34.2
  - org.jetbrains.exposed:exposed-dao:0.34.2
  - org.jetbrains.exposed:exposed-jdbc:0.34.2
  - org.xerial:sqlite-jdbc:3.36.0.2
  - io.github.monun:kommand:2.6.6
